apiVersion: v1
kind: Secret
metadata:
  name: workercontagemsecret
type: Opaque
data:
  ConnectionSqlServer: <STRING DE CONEXÃO DO SQL SERVER EM BASE 64>
  UsernameKafka: $ConnectionString <REPRESENTAR ESTE VALOR EM BASE 64>
  PasswordKafka: <CONNECTION STRING DO AZURE EVENT HUBS EM BASE 64>
  SaslKafka: plaintext <REPRESENTAR ESTE VALOR EM BASE 64>
  TlsKafka: enable <REPRESENTAR ESTE VALOR EM BASE 64>
  AppInsightsKey: <INSTRUMENTATION KEY DO AZURE APPLICATION INSIGHTS EM BASE 64>